version: 2
jobs:
  build-and-test:
    docker:
    - image: circleci/node:latest
    steps:
    - checkout
    - run:
        command: |
            docker build -t $DOCKER_LOGIN/$IMAGE_NAME -t $DOCKER_LOGIN/$IMAGE_NAME:$CIRCLE_BUILD_NUM-$CIRCLE_BRANCH .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_LOGIN/$IMAGE_NAME
workflows:
  build-and-test:
   jobs:
      - build-and-test